# frozen_string_literal: true

# Intructions
module HowToPlay
  def instructions
    puts <<~INSTRUCTIONS
      Mastermind is a code-breaking game. Your goal is to guess the secret code generated by the game.
      - The code is made up of colored guess pegs represented by letters.
      - Each time you guess, you`ll recieve feedback on the number of correct elements and their positions.
      - Use (q)uit to exit the game or (c)heat to reveal the secret code.

    INSTRUCTIONS
  end
end
